// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChDeXLGS57Jpb53-9yEIXkIEGYr3bEzEQ',
    appId: '1:791386335668:web:5a4e914e58df406aab2ae1',
    messagingSenderId: '791386335668',
    projectId: 'wall-tutorial',
    authDomain: 'wall-tutorial.firebaseapp.com',
    storageBucket: 'wall-tutorial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ORmg57MDPEEi5F40o0zivjKe2nyRP-k',
    appId: '1:791386335668:android:e1151d20e9be48faab2ae1',
    messagingSenderId: '791386335668',
    projectId: 'wall-tutorial',
    storageBucket: 'wall-tutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqj-u7WKsGMprQdH5ff2GWBWfuJ97Kn6w',
    appId: '1:791386335668:ios:0f203d8b2584585fab2ae1',
    messagingSenderId: '791386335668',
    projectId: 'wall-tutorial',
    storageBucket: 'wall-tutorial.appspot.com',
    iosClientId: '791386335668-48g1ct10ajcpc7a4s0i3vng0l6s38lnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqj-u7WKsGMprQdH5ff2GWBWfuJ97Kn6w',
    appId: '1:791386335668:ios:4175599d05c0ee0aab2ae1',
    messagingSenderId: '791386335668',
    projectId: 'wall-tutorial',
    storageBucket: 'wall-tutorial.appspot.com',
    iosClientId: '791386335668-st3q4g3v9u3a55qcrlsu4d89k5t7pk9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
